### PR TITLE
feat: update CI actions

### PR DESCRIPTION
**Pull request by hosekpeter**
Jira: [PSGO-399](https://keboola.atlassian.net/browse/PSGO-399)

**Changes:**
- updated version -> `docker/login-action@v3`
- updated version -> `actions/cache@v4`
- updated version -> `actions/setup-go@v5`
- updated version -> `actions/checkout@v4`

-----------

[PSGO-399]: https://keboola.atlassian.net/browse/PSGO-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by michaljurecko** [comment]
Can we fix these issues, or what are the next steps?

https://github.com/keboola/keboola-as-code/actions/runs/8109961818?pr=1632

image

**Comment by michaljurecko** [comment]
Petr, is it draft or for review? Reviewers are assigned, but type was draft, and the last commit is `WIP`.

**Comment by hosekpeter** [comment]
@michaljurecko  yes, it was draft, I can't to cancel a request for review.  I wanted to update a commit `WIP` and then to switch for review.

**Comment by michaljurecko** [comment]
:heavy_check_mark:  Ok, but you can :slightly_smiling_face: 

image

**Review by michaljurecko — APPROVED** [review]
LGTM

**Pull request merged**
