### PR TITLE
fix: Sentinel error instead of nil check.

### PR DESCRIPTION
**Pull request by Matovidlo**
**Changes:**
- fix: Sentinel error instead of nil check.
- fix: Move router pipeline creation under router.
- create utils.go in router package.
-----------

### CODE REVIEW

**Comment by Matovidlo** [comment]
@michaljurecko KCP test still fails

**Comment by michaljurecko** [comment]
@Matovidlo link please?

**Comment by Matovidlo** [comment]
@michaljurecko https://github.com/keboola/keboola-as-code/actions/runs/9903811027/job/27359999464?pr=1906

**Review by michaljurecko — APPROVED** [review]

**Comment by michaljurecko** [comment]
(I am rebasing it)

**Comment by michaljurecko** [comment]
(rebased)

**Pull request merged**
