### PR TITLE
Use Go standard project layout

### PR DESCRIPTION
**Pull request by webrouse**
Adresarova struktura upravena podla: https://github.com/golang-standards/project-layout

**Motivacia:** v dalsich taskoch (`DBT`, `pip install`) budem potrebovat volat nejake casti kodu z Python-u, ... preto budem potrebovat oddelit kod kniznice od interneho kodu, ... a na to sa dobre hodi ta standardna adresarova struktura.

**Prvy commit su iba `renames` + `.gitignore` uprava**, takze https://github.com/keboola/keboola-as-code/commit/ba5284baa7c20b5cbc9ee1624968f4c96c264af5 nemusis pozerat diff, staci pozriet novu adresarovu strukturu.
Dalsie commity su (male) zmeny v suboroch, v import cestach, ...

```
├── build - CI + packaging
├── cmd - CLI entrypoint
├── docs
├── internal - internal packages
├── pkg - public/library packages
├── scripts 
├── target - build output
├── test - functional tests
└── vendor - sync pkgs with IDE outside container
```

**Komentare su v jednotlivych commitoch, nejak to Github nevie spracovat s takymto velky, PR.**

### CODE REVIEW

**Comment by kacurez** [comment]
pozeram ze nesedia cesty pre gon:
https://github.com/keboola/keboola-as-code/blob/1b0e2fa44b5aae79cb5b9acdb88899dfae6613aa/.github/workflows/push.yml#L245-L246
Podobne aj pre homebrew:
https://github.com/keboola/keboola-as-code/blob/1b0e2fa44b5aae79cb5b9acdb88899dfae6613aa/.github/workflows/push.yml#L296
A ten template file `homebrew.template.rb` tam pre zmenu vobec nevidim

**Comment by kacurez** [comment]
aha uz ho vidim, sorry mi github nejak nevedel najst, viem preco
https://github.com/keboola/keboola-as-code/tree/webrouse-standard-layout/build/package/homebrew

**Comment by webrouse** [comment]
vdaka za upozornenie. zabudol som to upravit.

**Comment by kacurez** [comment]
jasne videl som ze vsetky build/test steps presli tak som sa namatkovo zameral na tie release steps ktore sa v PR nepustaju :)

**Comment by webrouse** [comment]
jj, ono ked neprejde release, ak by tam bola nejaka chyba, ktoru si nevsimneme, ... tak sa to proste fixne potom.
vykusam to hned, ked spravim dalsiu feature.

**Review by kacurez — APPROVED** [review]
super 👍

**Pull request merged**
