### PR TITLE
RFC-2023-008 branch

### PR DESCRIPTION
**Pull request by michaljurecko**
Jira: https://keboola.atlassian.net/browse/PSGO-285

Changes:
- Initialized `RFC-2023-008` branch with disabled linter and tests, so we can do reviews for smaller PRs.

-------------------

Rozmyslal som ako spravit vacsiu zmenu tak, aby to neboli obrovske PRs.
Tak som vytvoril novu branch, kde su aktualne vypnute testy.

V dalsich PRs budem pridavat jednotlive nove pkgs, so screenshotom unit testov.
Neskor sa upravia ostatne unit/E2E testy.
A nakoniec sa to cele posle uz s testami este raz na PR do `main` branch.

Branch som dal protected aby sa nezabudlo na nejaky review.

### CODE REVIEW

**Comment by michaljurecko** [comment]
Toto je vlastne zatial FYI, a nerobi sa review, az nakoniec.

**Comment by michaljurecko** [comment]
(rebased)

**Comment by michaljurecko** [comment]
(rebased)

**Comment by michaljurecko** [comment]
(Snyk will be fixed with dependencies update, in a next PR)

**Review by hosekpeter — APPROVED** [review]
LGTM

**Pull request merged**
